### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by sanerdk** [nbusseneau/rito-pls#1]
must be api changed over year :)

**Comment by nbusseneau** [comment]
Hey, sorry for late reply, I hadn't seen the notification!

Can't test right now but it's likely that the API has changed, yes. I recommend you use [LeagueWrap](https://github.com/paquettg/leaguewrap) for a full PVP.NET API. I'm part of a LAN organization and we used it instead of my custom implementation to retrieve match results.

Hope that helps :)
